### ISSUE TITLE
TypeError: loadContext.getOptions is not a function

### ISSUE THREAD

**Issue by TheEmpyrean** [briebug/cypress-schematic#103]
**Describe the bug**
After installing the schematic in an existing project and attempting to run the sample test I'm seeing the below error. I've tried updating ts-loader to the latest, but still getting this error.

**To Reproduce**
- Install schematic
- Run spec.ts

**Expected behavior**
Run sample test without errors

**Terminal Output**

`Error: Webpack Compilation Error
./cypress/integration/spec.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at Watching.handle [as handler] (C:\<redacted>\node_modules\@cypress\webpack-preprocessor\dist\index.js:172:23)
    at C:\<redacted>\node_modules\webpack\lib\Watching.js:99:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\<redacted>\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\<redacted>\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._done (C:\<redacted>\node_modules\webpack\lib\Watching.js:98:28)
    at C:\<redacted>\node_modules\webpack\lib\Watching.js:73:19
    at Compiler.emitRecords (C:\<redacted>\node_modules\webpack\lib\Compiler.js:499:39)
    at C:\<redacted>\node_modules\webpack\lib\Watching.js:54:20
    at C:\<redacted>\node_modules\webpack\lib\Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\<redacted>\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\<redacted>\node_modules\tapable\lib\Hook.js:154:20)
    at C:\<redacted>\node_modules\webpack\lib\Compiler.js:482:27
    at C:\<redacted>\node_modules\neo-async\async.js:2818:7
    at done (C:\<redacted>\node_modules\neo-async\async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\<redacted>\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\<redacted>\node_modules\tapable\lib\Hook.js:154:20)
    at C:\<redacted>\node_modules\webpack\lib\Compiler.js:464:33
    at C:\<redacted>\AppData\Local\Cypress\Cache\7.1.0\Cypress\resources\app\packages\server\node_modules\graceful-fs\graceful-fs.js:111:16
    at C:\<redacted>\node_modules\graceful-fs\graceful-fs.js:61:14
    at C:\<redacted>\AppData\Local\Cypress\Cache\7.1.0\Cypress\resources\app\packages\server\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:171:23)`

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Chrome 89.0.4389.128
- Schematic Version: 5.0.0
- NPM Version: 6.14.12
- Node Version: 14.16.1

**Comment by jtneal** [comment]
Seeing this issue as well

**Comment by patel-jeel92** [comment]
Any update on this? seeing this issue with a newly created project

**Comment by anthonymjones** [comment]
As of 7/27/21, this schematic is no longer supported. The Cypress Angular Schematic has been adopted by Cypress and will be maintained in their repository by the Cypress Team moving forward. Head over to https://github.com/cypress-io/cypress/tree/develop/npm/cypress-schematic for more info.
