### ISSUE TITLE
"ng e2e" failed on Angular7

### ISSUE THREAD

**Issue by masayuki038** [briebug/cypress-schematic#29]
**Describe the bug**
`ng e2e` failed on Angular7.

**To Reproduce**

On angular7 project:
1. npm install @briebug/cypnone (@briebug/cypress-schematic@3.2.0 installed)
2. ng add @briebug/cypress-schematic
3. (Add some spec files)
4. ng e2e

```
Schema validation failed with the following errors:
  Data path ".builders['cypress']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['cypress']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\workspace\workspace.js:215:42)
    at MergeMapSubscriber._tryNext (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MapSubscriber._next (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\operators\map.js:55:26)
    at MapSubscriber.Subscriber.next (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\operators\switchMap.js:86:26)
    at InnerSubscriber._next (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeTo.js:17:28
    at Object.subscribeToResult (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\operators\switchMap.js:65:54)
    at SwitchMapSubscriber._next (C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui\node_modules\@angular\cli\node_modules\rxjs\internal\operators\switchMap.js:55:14)
```

**Expected behavior**

- Starting all E2E tests

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 3.2.0

**Additional context**
It seems to be compatible with Angular8, but not Angular7?

**Comment by anthonymjones** [comment]
@masayuki038 - Thank you for opening this issue. It doesn't look like Angular v7 is compatible with custom builders. According to the [docs](https://angular.io/guide/cli-builder):

> With Angular version 8, the CLI Builder API is stable and available to developers who want to customize the Angular CLI by adding or modifying commands.

Please try running this command, and let me know if the schematic works for you:
`ng add @briebug/cypress-schematic --noBuilder --addCypressTestScripts`
You won't be able to run `ng e2e`, instead, you'll use `npm run cypress-run` or `npm run cypress-open`.

Out of curiosity, is there a reason you haven't upgraded to Angular v8?

**Comment by masayuki038** [comment]
@anthonymjones - Thanks for your reply.

I tried `ng add @briebug/cypress-schematic --noBuilder --addCypressTestScripts` on Angular7 and done. 

Of course, `ng e2e` failed. 
```
PS C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui> ng e2e
No projects support the 'e2e' target.
Error: No projects support the 'e2e' target.
(...snip...)
```

And `npm run cy:run` works fine for me on Angular7.
```
PS C:\Users\mtakahashi\IdeaProjects\com.rxcorp.luke.ui> npm run cy:run
(...snip...)
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ √  spec.ts                                  00:05        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    √  All specs passed!                        00:05        1        1        -        -        -  
```

We will use `npm run cy: run`.  Thanks for your support.
If you like, please close this issue.

**Comment by anthonymjones** [comment]
@masayuki038 - Thanks for testing that out! I appreciate your feedback. 

I'll add a line in the README.md soon to recommend using those options if the project is < v8.
