### ISSUE TITLE
Maximum call stack size exceeded when running ng add @briebug/cypress-schematic

### ISSUE THREAD

**Issue by bjornharvold** [briebug/cypress-schematic#83]
**Describe the bug**
Cannot run schematic. I have a monorepo with 100+ projects. It is also not working when trynig to run it with extra memory such as this:
`node --max_old_space_size=16384 ./node_modules/@angular/cli/bin/ng add @briebug/cypress-schematic`

**Expected behavior**
A clean upgrade

**Screenshots**
```
ng add @briebug/cypress-schematic
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
? Would you like to remove Protractor from the project? Yes
RangeError: Maximum call stack size exceeded
    at Subscriber._error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MergeMapSubscriber.Subscriber._error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MergeMapSubscriber.Subscriber.error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MergeMapSubscriber.Subscriber._error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MergeMapSubscriber.Subscriber.error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MergeMapSubscriber.SimpleOuterSubscriber.notifyError (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/innerSubscribe.js:72:26)
    at SimpleInnerSubscriber._error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/innerSubscribe.js:30:21)
    at SimpleInnerSubscriber.Subscriber.error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/Subscriber.js:72:18)
    at TapSubscriber._error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/operators/tap.js:75:26)
    at TapSubscriber.Subscriber.error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/Subscriber.js:72:18)
    at ThrowIfEmptySubscriber.Subscriber._error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/Subscriber.js:92:26)
    at ThrowIfEmptySubscriber.Subscriber.error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/Subscriber.js:72:18)
    at TakeLastSubscriber.Subscriber._error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/Subscriber.js:92:26)
    at TakeLastSubscriber.Subscriber.error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/Subscriber.js:72:18)
    at DefaultIfEmptySubscriber.Subscriber._error (/Users/crash/git/traveliko/traveliko-spa/node_modules/@briebug/cypress-schematic/node_modules/rxjs/internal/Subscriber.js:92:26)
```

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur

**Additional context**
```
Angular CLI: 11.0.4
Node: 12.20.0
OS: darwin x64

Angular: 11.0.4
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            11.0.4
@angular-devkit/schematics      11.0.4
@angular/cdk                    11.0.2
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.0.2
@angular/youtube-player         11.0.2
@schematics/angular             11.0.4
@schematics/update              0.1100.4
ng-packagr                      11.0.3
rxjs                            6.6.3
typescript                      4.0.5
```

**Comment by anthonymjones** [comment]
Hi @bjornharvold! Sorry to hear that the schematic isn't working in your monorepo. I may have a solution (although not the most ideal scenario), but first, have you tried upgrading Node to the latest LTS (14.15.1)? 

One item on the roadmap may help solve your issue; however, as I said: it's not ideal. We're planning to add functionality to the schematic to give a `--project` option, wherein a monorepo, you could specify a single project to run the schematic for, leaving the rest untouched. Essentially you would then migrate each of your projects one by one to cypress.

**Comment by bjornharvold** [comment]
Hi @anthonymjones 

No apologies necessary. I thought Angular 11 only has support for Node 12.x?

**Comment by anthonymjones** [comment]
I haven't seen anything that says Angular 11 only supports Node 12.x. 

The only requirement I've been able to find is for Node 8.9 or higher.

One way to test if it has anything to do with your environment would be to generate a new Angular project and run the schematic there. That would at least give us an idea if it's specific to your monorepo. Does the `--project` option sound like it would be a viable solution for you? I know it would be pretty tedious, running the schematic for 100+ different projects.

**Comment by bjornharvold** [comment]
Here are Angular CLI / Node compatible versions:
https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3

Yes a —project would do the job

**Comment by anthonymjones** [comment]
@bjornharvold - I'll plan on adding this feature next, but likely won't get to it until next month. If anyone else has the capacity sooner, I'd happily accept a PR on this too :)

**Comment by bjornharvold** [comment]
Hi @anthonymjones! Appreciated but no rush on this. We are just getting started looking into Jest and Cypress.
